### ISSUE TITLE
package the binary in a docker container

### ISSUE THREAD

**Issue by kaspernissen** [lunarway/snyk_exporter#1]
Wrapping the binary in a docker container would make the usability of the project better. A simple example of a docker run with the arguments to deploy and run this container.

**Comment by Crevil** [comment]
This is almost ready. Travis is building ATM.

I've added a Docker file for development and one for goreleaser. The latter just adds the compiled binary that is released to GitHub in a docker image.

**Comment by Crevil** [comment]
Docker images are now available on [quay.io/lunarway/snyk_exporter](https://quay.io/lunarway/snyk_exporter)
