### ISSUE TITLE
Add GitHub metadata to metrics 

### ISSUE THREAD

**Issue by omerlh** [lunarway/snyk_exporter#12]
Adding metadata like the team defined as owner of the repository could be interesting, what do you think?

**Comment by Crevil** [comment]
Where do can we collect this information? Are you thinking about looking the data up or providing a mapping to the Snyk projects as arguments?

**Comment by omerlh** [comment]
I think you should be able to get the name of the repo from Snyk and than query GitHub API using a token with repo:read scope.

**Comment by Crevil** [comment]
All right. On the top of my head, it seems a bit out of scope of this project. 

Another way would be to have a dedicated GitHub exporter with the repo name and owners exposed and then join the metrics within prometheus. I don't know if such an exporter already exists.

**Comment by omerlh** [comment]
Great idea, I'll check it out!
