### ISSUE TITLE
Filter ignored issues

### ISSUE THREAD

**Issue by omerlh** [lunarway/snyk_exporter#15]
Currently, the request to get issues does not filter ignored issues:
```
postData := issuesPostData{
		Filters: issueFilters{
			Severities: []string{
				"high", "medium", "low",
			},
		},
	}
```
See the [API documentation](https://snyk.docs.apiary.io/#reference/projects/project-issues/list-all-issues) for more details. I'm working on a fix PR.

**Comment by kaspernissen** [comment]
That's awesome, we actually had this on our roadmap within the next month or so. Thank you for working on it!

**Comment by omerlh** [comment]
I just tested it, I can confirm it's working 🎉 Thank you!

**Comment by Crevil** [comment]
Thank you for your contributions 🙏
