### ISSUE TITLE
Upgrading to v1.3.1 produces unexpected crashes

### ISSUE THREAD

**Issue by yaron-idan** [lunarway/snyk_exporter#26]
**Describe the bug**
Upgrading the exporter from v1.2.0->v1.3.1 is causing it to crash multiple times a day. The exporter is running on kubernetes and crashes when it's liveness probe tries to access /healthz and gets the following error - `net/http: request canceled (Client.Timeout exceeded while awaiting headers)`.

**To Reproduce**
1. Publish the exporter as a k8s pod, with `/healthz` configured as the liveness probe
2. Wait for a few hours until the pod crashes.

**Expected behavior**
The container health check should either return a healthy response or produce a descriptive error of the cause for crashing.

**Application (please complete the following information):**
 - Distribution: Docker image
 - Version 1.3.1

**Log output (if applicable):**
This log record is printed just before the pod crashes, but it's probably the sigterm received from k8s causing it - 
```
time="2019-07-15T07:24:58Z" level=error msg="Snyk exporter exited due to error: received os signal 'terminated'" source="main.go:119"
```

**Additional context**
Exporter is running fine on v1.2.0. I will try to bisect the issue to a specific release and perhaps narrow it down to a specific feature by gradually incrementing the exporter version and update when I have more info.

**Comment by Crevil** [comment]
Thank you for reporting this detailed bug report. I'll look into it and see what change introduced the bug.

**Comment by Crevil** [comment]
The `/healthz` endpoint will immediately return `healthy` when the application starts. As [seen in the code](https://github.com/lunarway/snyk_exporter/blob/a22333ac5eb9b30a5880cf965294201004209b29/main.go#L80-L82) there is no logic in this endpoint.

How is your liveness probes set up? With what values? And where do you see the `Client.Timeout` error? Is that from the k8s logs?

**Comment by Crevil** [comment]
@yaron-idan Could you provide some more details to this issue?

**Comment by Crevil** [comment]
As we have not head anything in over a month I'm closing this one. Feel free to reopen if still applicable.
