### ISSUE TITLE
Add /healthz endpoint for kubernetes probes

### ISSUE THREAD

**Issue by omerlh** [lunarway/snyk_exporter#7]
For easy kubernetes monitoring, we need to provide readyness and liveness probes. The `/healthz` should always return true, I would like to have `/ready` that returns true only if the initial scrap completed. So the pod will get traffic only when it finish scarping, and expose the correct metrics

**Comment by Crevil** [comment]
Can you ellaborate what the `healthz` endpoint is needed for? You can use the metrics endpoint for liveness I guess. Kunernetes only requires it to return a starus 200 as far as I know.

Adding `ready` makes fine sense to me.

**Comment by omerlh** [comment]
yep, that why I added an endpoint that always returns 200 - `/healthz`. We can reuse maybe the same endpoint, but I assumed it is better to separate the endpoints.

**Comment by Crevil** [comment]
Ok. Fine by me. Is it a conventional name, `healthz`? I don’t think I’ve seen that before.

**Comment by omerlh** [comment]
Yep, see an example [here](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#define-a-liveness-http-request) - from the official doc. You can see the same behavior on Prometheus, for example.

**Comment by Crevil** [comment]
Makes good sense. Thanks for clearing that out.
