### ISSUE TITLE
Adding "isFixed" as a parameter

### ISSUE THREAD

**Issue by sethkdv** [lunarway/snyk_exporter#81]
The Reporting API under "Get List of Issues" https://snyk.docs.apiary.io/#reference/reporting-api/issues/get-list-of-issues includes a filter "isFixed". This would allow you to calculate the number of fixed vulnerabilities needed for displaying burn down rate.

I highly recommend adding this in. Please let me know if you have any questions regarding this feature request. 

![image](https://user-images.githubusercontent.com/108430222/176685381-a9b90448-cc63-4c11-b946-ac614fd56515.png)

**Comment by hoeg** [comment]
Hi @sethkdv 🚀 

Thank you for opening this issue! Sounds like a great idea 👌 Would you be up for creating a pull request adding this parameter? We would be happy to review and make a release afterwards :)

**Comment by nixboot** [comment]
Hi. Thanks for your interest in the project. We are not maintaining it anymore, and are archiving it for now.
