### ISSUE TITLE
Read API token from a configuration file

### ISSUE THREAD

**Issue by omerlh** [lunarway/snyk_exporter#9]
Some might argue that it is not a good practice to read sensitive information from an env var. What do you think on reading the API key from a config file?

**Comment by Crevil** [comment]
It is not read from the env. It’s a command line flag. 

We’ve only shown a kubernetes example where we read it from the environment and into a command line flag.

That being set, it might be useful to be able to read from a file as well. What deployment environments do you use where this makes sense?

**Comment by omerlh** [comment]
Yes, sorry for not being clear enough.
My plan is to use [Kamus](https://github.com/Soluto/kamus) for encrypting Snyk API token. Kamus let me decrypt it into a configuration file. Because the image is scratch, I have nothing (not even bash) that I can leverage to do things like `"--snyk.api-token", "$(cat /secrets/snyk-apy-key.txt)"`. So I must either change the code or change the base image.

**Comment by Crevil** [comment]
Makes sense. I’ll see if I can add support for it tomorrow 👍

**Comment by omerlh** [comment]
I can also do that, just wanted to make sure my PR will be accepted first :) Want me to do both on the same PR?

**Comment by Crevil** [comment]
I’d like to keep it separate to make it clear for future reference. Feel free to submit a PR! 🙌

I believe `kingpin` has some support for it already.

**Comment by omerlh** [comment]
Sure, that totally makes sense :) I'll take a look tomorrow morning. 
BTW thank you for being that responsive :) It so good to work on OSS in such situation!

**Comment by omerlh** [comment]
Haha, good news - kingpin supports it out of the box:
```
 echo --snyk.api-token=<>\n > args
```
And run the exporter using:
```
./snyk-exporter @args
```

**Comment by Crevil** [comment]
Interesting. Can you explain the syntax? I'll add it to the README for future reference then.

Is it just a file with the actual args as if they were on the command line?

**Comment by omerlh** [comment]
Yes, I added an example to the readme of kingpin (see alecthomas/kingpin#262). Want me to open a PR to the readme?

**Comment by Crevil** [comment]
Please do. Thank you for your time
